import math
print("ceil",math.ceil(3.56))
print("floor",math.floor(3.65))
print("fabs",math.fabs(-3.3))
print("abs-buitlin",abs(-3))
print("trun-removes decimal pts",math.trunc(3.65))
print("pow-int",pow(2,3))
print("math.pow-float",math.pow(2,3))
print("sqrt",math.sqrt(4))
print("log(10)",math.log(10))
print("log2",math.log2(8))
print("log inbuilt",math.log(8,2))
print("fact",math.factorial(5))
print("gcd",math.gcd(8,4))
print("lcm",math.lcm(2,5))
print("perm",math.perm(2,3))
print("comb",math.comb(2,3))
print("isclose",math.isclose(2.3,2))
print("isNan",math.isnan(345))
print("inf",math.isinf(3123124))
print("inf val",math.inf)
print("pi",math.pi)
print("exp",math.e)