import os
print(os.name)
print(os.getcwd)
print(os.mkdir("modules"))
print(os.rmdir("modules"))
print(os.makedirs("modules/builtin"))
print(os.removedirs("modules/builtin"))
print(os.path.exists("eiebfih"))
print(os.path.isfile("op.txt"))
print(os.path.isdir("adv_py"))
print(os.path.basename("k/l/m.txt"))
print(os.path.dirname("k/l/m.txt"))
print(os.environ)
print(os.environ.get("HOME"))
print(os.system("echo helloworld"))
print(os.getpid)
print(os.getppid)
